<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Connection;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function add(array $list)
    {
        $table = $this
            ->getEntityManager()
            ->getClassMetadata('AppBundle:City')
            ->getTableName();

        /* @var $connection Connection */
        $connection = $this->getEntityManager()->getConnection();

        $connection->exec("TRUNCATE TABLE `$table`;`");

        $statement = $connection->prepare("
            INSERT INTO `$table`(`alias`, `name`)
            VALUE (:alias, :name);
        ");

        $connection->beginTransaction();
        foreach ($list as $city) {
            $statement->execute($city);
        }
        $connection->commit();
    }
}
