<?php

namespace AppBundle\Repository;
use AppBundle\Entity\DeveloperProfile;
use AppBundle\Entity\DeveloperProfileSkillLink;
use AppBundle\Entity\Skill;

/**
 * DeveloperProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteSkill(DeveloperProfile $developerProfile, Skill $skill)
    {
        $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->delete(DeveloperProfileSkillLink::class, 'dpsl')
            ->where(
                'dpsl.developerProfile = :developerProfile',
                'dpsl.skill = :skill'
            )
            ->setParameters([
                'developerProfile' => $developerProfile,
                'skill' => $skill,
            ])
            ->getQuery()
            ->execute();
    }

    public function updateSkill(DeveloperProfile $developerProfile, Skill $skill, $score)
    {
        $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->update(DeveloperProfileSkillLink::class, 'dpsl')
            ->set('dpsl.score', $score)
            ->where(
                'dpsl.developerProfile = :developerProfile',
                'dpsl.skill = :skill'
            )
            ->setParameters([
                'developerProfile' => $developerProfile,
                'skill' => $skill,
            ])
            ->getQuery()
            ->execute();
    }
}
