<?php

namespace AppBundle\Repository;

/**
 * DeveloperProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
