<?php

namespace AppBundle\Repository;

/**
 * EmployerProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployerProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
