<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Connection;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function add(array $list)
    {
        $table = $this
            ->getEntityManager()
            ->getClassMetadata('AppBundle:Skill')
            ->getTableName();

        /* @var $connection Connection */
        $connection = $this->getEntityManager()->getConnection();

        $connection->exec("DELETE FROM `$table`;`");

        $statement = $connection->prepare("
            INSERT INTO `$table`(`alias`, `name`)
            VALUE (:alias, :name);
        ");

        $connection->beginTransaction();
        foreach ($list as $skill) {
            $statement->execute($skill);
        }
        $connection->commit();
    }

    public function getList()
    {
        return $this
            ->createQueryBuilder('s')
            ->select('s.alias', 's.name')
            ->getQuery()
            ->getArrayResult();
    }
}
