<?php

namespace AppBundle\Repository;

/**
 * SkillSynonymRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillSynonymRepository extends \Doctrine\ORM\EntityRepository
{
}
