<?php

namespace AppBundle\Repository;

/**
 * SkillPriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillPriorityRepository extends \Doctrine\ORM\EntityRepository
{
}
