<?php

namespace AppBundle\Repository;

/**
 * SocialProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUnique($socialCode, $profileId)
    {
        return $this
            ->createQueryBuilder('s')
            ->select('s, u')
            ->join('s.user', 'u')
            ->where(
                's.profileId = :profileId',
                's.socialCode = :socialCode'
            )
            ->setParameters([
                'socialCode' => $socialCode,
                'profileId' => $profileId,
            ])
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
}
