# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        oauth.user_provider:
            id: oauth.user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook: /login/oauth/check-facebook
                    google: /login/oauth/check-google
                    linkedin: /login/oauth/check-linkedin
                    github: /login/oauth/check-github
                    bitbucket: /login/oauth/check-bitbucket
                login_path:  /login # path if failed
                use_forward: false
                failure_path: /login
                default_target_path: /developers

                oauth_user_provider:
                    service: oauth.user_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
