developer.profile:
    path:     /edit
    defaults: { _controller: 'AppBundle:DeveloperProfile:edit' }
    methods:  ['GET', 'POST']

developer.profile.skills:
    path:     /skills
    defaults: { _controller: 'AppBundle:DeveloperProfile:skills' }
    methods:  ['GET']