developer.profile.edit:
    path:     /edit
    defaults: { _controller: 'AppBundle:DeveloperProfile:edit' }
    methods:  ['GET', 'POST']

developer.profile.edit.skills:
    path:     /edit/skills
    defaults: { _controller: 'AppBundle:DeveloperProfile:skills' }
    methods:  ['GET']