developer_profile_index:
    path:     /
    defaults: { _controller: "AppBundle:DeveloperProfile:index" }
    methods:  GET

developer_profile_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:DeveloperProfile:show" }
    methods:  GET

developer_profile_new:
    path:     /new
    defaults: { _controller: "AppBundle:DeveloperProfile:new" }
    methods:  [GET, POST]

developer_profile_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:DeveloperProfile:editById" }
    methods:  [GET, POST]

developer_profile:
    path:     /edit
    defaults: { _controller: "AppBundle:DeveloperProfile:edit" }
    methods:  [GET, POST]

developer_profile_skills:
    path:     /skills
    defaults: { _controller: "AppBundle:DeveloperProfile:skills" }
    methods:  [GET]