intro:
    path: /
    defaults: { _controller: AppBundle:Intro:index }
    methods: ['GET']

developers.page:
    path:     /developers
    defaults: { _controller: AppBundle:Developer:list }
    methods: ['GET']