app_developer_profile:
    resource: "@AppBundle/Resources/config/routing/developerprofile.yml"
    prefix:   /developer/profile

intro:
    path: /
    defaults: { _controller: AppBundle:Intro:index }
    methods: ['GET']

developers.city.page:
    path:     /developers/{city}
    defaults: { _controller: AppBundle:Developer:city }
    methods: ['GET']
    requirements:
        city: '[A-z-]+'

developers.page:
    path:     /developers
    defaults: { _controller: AppBundle:Developer:list }
    methods: ['GET']

developer:
    path:     /developer/{id}
    defaults: { _controller: AppBundle:Developer:profile }
    methods: ['GET']
    requirements:
        id: '\d+'