app.developer.profile:
    resource: '@AppBundle/Resources/config/routing/developer.profile.yml'
    prefix:   /developer/profile

app.employer.profile:
    resource: '@AppBundle/Resources/config/routing/employer.profile.yml'
    prefix:   /employer/profile

intro:
    path: /
    defaults: { _controller: AppBundle:Intro:index }
    methods: ['GET']

developers.city.page:
    path:     /developers/{city}
    defaults: { _controller: AppBundle:Developer:city }
    methods: ['GET']
    requirements:
        city: '[A-z-]+'

developers.page:
    path:     /developers
    defaults: { _controller: AppBundle:Developer:list }
    methods: ['GET']

developer.profile:
    path:     /developer/{id}
    defaults: { _controller: AppBundle:Developer:profile }
    methods: ['GET']
    requirements:
        id: '\d+'

developer.external:
    path:     /developer/external/{id}
    defaults: { _controller: AppBundle:Developer:external }
    methods: ['GET']
    requirements:
        id: '\d+'

debug.dump:
    path:     /dump
    defaults: { _controller: AppBundle:Debug:dump }
    methods: ['GET']