services:
    senseye.elasticsearch.client:
        class: 'Elastica\Client'

    senseye.profile.search.request.analyzer:
        class: 'AppBundle\Service\ProfileSearchRequestAnalyzer'

    senseye.profile.searcher:
        class: 'AppBundle\Service\ProfileSearcher'
        arguments:
            - '@senseye.elasticsearch.client'