services:
    senseye.elasticsearch.client:
        class: 'Elastica\Client'

    senseye.pager.factory:
        class: 'ReenExeCubeTime\LightPaginator\CompleteFactory'

    senseye.profile.search.request.analyzer:
        class: 'AppBundle\Service\ProfileSearchRequestAnalyzer'

    senseye.profile.search.builder:
        class: 'AppBundle\Service\ProfileSearchBuilder'

    senseye.profile.searcher:
        class: 'AppBundle\Service\ProfileSearcher'
        arguments:
            - '@senseye.elasticsearch.client'
            - '@senseye.profile.search.builder'
            - '@senseye.pager.factory'