AppBundle\Entity\EmployerProfile:
    type: entity
    table: s_employer_profile
    repositoryClass: AppBundle\Repository\EmployerProfileRepository

    indexes:
        USER_ID_INDEX:
            columns:
                - user_id

    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            joinColumns:
                -
                    name: user_id
                    nullable: false
                    referencedColumnName: id
            fetch: EXTRA_LAZY

    id:
        id:
            type: integer
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY

    fields:
        title:
            type: string
            nullable: false
            length: 255
        description:
            type: text
            nullable: false
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false