AppBundle\Entity\SkillSynonym:
    type: entity
    table: s_skill_synonym
    repositoryClass: AppBundle\Repository\SkillSynonymRepository

    uniqueConstraints:
        UNIQUE_SYNONYM_ALIAS:
            columns:
                - alias
                - synonym

    id:
        id:
            type: integer
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY

    fields:
        alias:
            type: string
            nullable: false
            length: 255
            fixed: false
        synonym:
            type: string
            nullable: false
            length: 255
            fixed: false