services:
    senseye.elasticsearch.client:
        class: 'Elastica\Client'
        arguments:
            - host: '%elastic_host%'
              port: '%elastic_port%'

    senseye.developer.index:
        class: 'AppBundle\Service\DeveloperIndexService'
        arguments:
            - '@senseye.elasticsearch.client'

    senseye.pager.factory:
        class: 'ReenExeCubeTime\LightPaginator\CompleteFactory'

    senseye.profile.search.request.analyzer:
        class: 'AppBundle\Service\ProfileSearchRequestAnalyzer'

    senseye.profile.search.builder:
        class: 'AppBundle\Service\ProfileSearchBuilder'

    senseye.profile.searcher:
        class: 'AppBundle\Service\ProfileSearcher'
        arguments:
            - '@senseye.developer.index'
            - '@senseye.profile.search.builder'
            - '@senseye.pager.factory'

    senseye.profile.available.criteria.repository:
        class: 'AppBundle\Service\ProfileAvailableCriteriaRepository'
        arguments:
            - '@senseye.developer.index'

    senseye.profile.counter:
        class: 'AppBundle\Service\ProfileCounter'
        arguments:
            - '@senseye.developer.index'
            - '@senseye.profile.search.builder'

    senseye.profile.criteria.container:
        class: 'AppBundle\Service\ProfileSearchCriteriaContainerService'

    senseye.seo:
        class: 'AppBundle\Service\SeoService'